function Hd = filtertest
%FILTERTEST 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 06-Jul-2025 17:54:09

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 11.2;  % Sampling Frequency

Fpass = 4.4;             % Passband Frequency
Fstop = 4.7;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
