function Hd = filtery
%FILTERY 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 21-May-2025 16:16:25

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 22.4;  % Sampling Frequency

N     = 100;  % Order
Fpass = 5;    % Passband Frequency
Fstop = 7;    % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 1;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
